on: pull_request
name: CI
jobs:
  test:
    name: Test Suite
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          set -o pipefail && xcodebuild -project ForemWebView.xcodeproj -scheme Example -sdk iphonesimulator -destination "${destination}" test | xcpretty
        env:
         DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
         destination: ${{ matrix.destination }}
